# Generated by Django 4.2.5 on 2023-10-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=10)),
                ('emailid', models.CharField(max_length=50)),
                ('gstin', models.CharField(max_length=15)),
            ],
        ),
    ]
