# Generated by Django 4.2.5 on 2023-10-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='pan',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
